/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package signplates.init;

import signplates.block.PlateZBlock;
import signplates.block.PlateYBlock;
import signplates.block.PlateXBlock;
import signplates.block.PlateWaterBlock;
import signplates.block.PlateWBlock;
import signplates.block.PlateVBlock;
import signplates.block.PlateUBlock;
import signplates.block.PlateTBlock;
import signplates.block.PlateStopBlock;
import signplates.block.PlateSBlock;
import signplates.block.PlateRBlock;
import signplates.block.PlateQBlock;
import signplates.block.PlatePlusBlock;
import signplates.block.PlatePBlock;
import signplates.block.PlateOBlock;
import signplates.block.PlateNBlock;
import signplates.block.PlateMoneyBlock;
import signplates.block.PlateMinusBlock;
import signplates.block.PlateMBlock;
import signplates.block.PlateLightBlock;
import signplates.block.PlateLBlock;
import signplates.block.PlateKBlock;
import signplates.block.PlateJBlock;
import signplates.block.PlateIncorrectBlock;
import signplates.block.PlateIBlock;
import signplates.block.PlateHeartBlock;
import signplates.block.PlateHBlock;
import signplates.block.PlateGBlock;
import signplates.block.PlateFireBlock;
import signplates.block.PlateFacesadBlock;
import signplates.block.PlateFaceneutralBlock;
import signplates.block.PlateFacemadBlock;
import signplates.block.PlateFacehappyBlock;
import signplates.block.PlateFacecatBlock;
import signplates.block.PlateFBlock;
import signplates.block.PlateEmptyBlock;
import signplates.block.PlateElectricityBlock;
import signplates.block.PlateEBlock;
import signplates.block.PlateDangerBlock;
import signplates.block.PlateDBlock;
import signplates.block.PlateCorrectBlock;
import signplates.block.PlateCBlock;
import signplates.block.PlateBonusBlock;
import signplates.block.PlateBBlock;
import signplates.block.PlateArrowupBlock;
import signplates.block.PlateArrowrightBlock;
import signplates.block.PlateArrowleftBlock;
import signplates.block.PlateArrowdownBlock;
import signplates.block.PlateABlock;
import signplates.block.Plate9Block;
import signplates.block.Plate8Block;
import signplates.block.Plate7Block;
import signplates.block.Plate6Block;
import signplates.block.Plate5Block;
import signplates.block.Plate4Block;
import signplates.block.Plate3Block;
import signplates.block.Plate2Block;
import signplates.block.Plate1Block;
import signplates.block.Plate0Block;

import signplates.SignPlatesMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

public class SignPlatesModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(SignPlatesMod.MODID);
	public static final DeferredBlock<Block> PLATE_A = REGISTRY.register("plate_a", PlateABlock::new);
	public static final DeferredBlock<Block> PLATE_B = REGISTRY.register("plate_b", PlateBBlock::new);
	public static final DeferredBlock<Block> PLATE_C = REGISTRY.register("plate_c", PlateCBlock::new);
	public static final DeferredBlock<Block> PLATE_D = REGISTRY.register("plate_d", PlateDBlock::new);
	public static final DeferredBlock<Block> PLATE_E = REGISTRY.register("plate_e", PlateEBlock::new);
	public static final DeferredBlock<Block> PLATE_F = REGISTRY.register("plate_f", PlateFBlock::new);
	public static final DeferredBlock<Block> PLATE_G = REGISTRY.register("plate_g", PlateGBlock::new);
	public static final DeferredBlock<Block> PLATE_H = REGISTRY.register("plate_h", PlateHBlock::new);
	public static final DeferredBlock<Block> PLATE_I = REGISTRY.register("plate_i", PlateIBlock::new);
	public static final DeferredBlock<Block> PLATE_J = REGISTRY.register("plate_j", PlateJBlock::new);
	public static final DeferredBlock<Block> PLATE_K = REGISTRY.register("plate_k", PlateKBlock::new);
	public static final DeferredBlock<Block> PLATE_L = REGISTRY.register("plate_l", PlateLBlock::new);
	public static final DeferredBlock<Block> PLATE_M = REGISTRY.register("plate_m", PlateMBlock::new);
	public static final DeferredBlock<Block> PLATE_N = REGISTRY.register("plate_n", PlateNBlock::new);
	public static final DeferredBlock<Block> PLATE_O = REGISTRY.register("plate_o", PlateOBlock::new);
	public static final DeferredBlock<Block> PLATE_P = REGISTRY.register("plate_p", PlatePBlock::new);
	public static final DeferredBlock<Block> PLATE_R = REGISTRY.register("plate_r", PlateRBlock::new);
	public static final DeferredBlock<Block> PLATE_S = REGISTRY.register("plate_s", PlateSBlock::new);
	public static final DeferredBlock<Block> PLATE_T = REGISTRY.register("plate_t", PlateTBlock::new);
	public static final DeferredBlock<Block> PLATE_Q = REGISTRY.register("plate_q", PlateQBlock::new);
	public static final DeferredBlock<Block> PLATE_U = REGISTRY.register("plate_u", PlateUBlock::new);
	public static final DeferredBlock<Block> PLATE_V = REGISTRY.register("plate_v", PlateVBlock::new);
	public static final DeferredBlock<Block> PLATE_W = REGISTRY.register("plate_w", PlateWBlock::new);
	public static final DeferredBlock<Block> PLATE_X = REGISTRY.register("plate_x", PlateXBlock::new);
	public static final DeferredBlock<Block> PLATE_Y = REGISTRY.register("plate_y", PlateYBlock::new);
	public static final DeferredBlock<Block> PLATE_Z = REGISTRY.register("plate_z", PlateZBlock::new);
	public static final DeferredBlock<Block> PLATE_EMPTY = REGISTRY.register("plate_empty", PlateEmptyBlock::new);
	public static final DeferredBlock<Block> PLATE_0 = REGISTRY.register("plate_0", Plate0Block::new);
	public static final DeferredBlock<Block> PLATE_1 = REGISTRY.register("plate_1", Plate1Block::new);
	public static final DeferredBlock<Block> PLATE_2 = REGISTRY.register("plate_2", Plate2Block::new);
	public static final DeferredBlock<Block> PLATE_3 = REGISTRY.register("plate_3", Plate3Block::new);
	public static final DeferredBlock<Block> PLATE_4 = REGISTRY.register("plate_4", Plate4Block::new);
	public static final DeferredBlock<Block> PLATE_5 = REGISTRY.register("plate_5", Plate5Block::new);
	public static final DeferredBlock<Block> PLATE_6 = REGISTRY.register("plate_6", Plate6Block::new);
	public static final DeferredBlock<Block> PLATE_7 = REGISTRY.register("plate_7", Plate7Block::new);
	public static final DeferredBlock<Block> PLATE_8 = REGISTRY.register("plate_8", Plate8Block::new);
	public static final DeferredBlock<Block> PLATE_9 = REGISTRY.register("plate_9", Plate9Block::new);
	public static final DeferredBlock<Block> PLATE_PLUS = REGISTRY.register("plate_plus", PlatePlusBlock::new);
	public static final DeferredBlock<Block> PLATE_MINUS = REGISTRY.register("plate_minus", PlateMinusBlock::new);
	public static final DeferredBlock<Block> PLATE_ARROWUP = REGISTRY.register("plate_arrowup", PlateArrowupBlock::new);
	public static final DeferredBlock<Block> PLATE_ARROWDOWN = REGISTRY.register("plate_arrowdown", PlateArrowdownBlock::new);
	public static final DeferredBlock<Block> PLATE_ARROWLEFT = REGISTRY.register("plate_arrowleft", PlateArrowleftBlock::new);
	public static final DeferredBlock<Block> PLATE_ARROWRIGHT = REGISTRY.register("plate_arrowright", PlateArrowrightBlock::new);
	public static final DeferredBlock<Block> PLATE_MONEY = REGISTRY.register("plate_money", PlateMoneyBlock::new);
	public static final DeferredBlock<Block> PLATE_FACEHAPPY = REGISTRY.register("plate_facehappy", PlateFacehappyBlock::new);
	public static final DeferredBlock<Block> PLATE_FACESAD = REGISTRY.register("plate_facesad", PlateFacesadBlock::new);
	public static final DeferredBlock<Block> PLATE_FACEMAD = REGISTRY.register("plate_facemad", PlateFacemadBlock::new);
	public static final DeferredBlock<Block> PLATE_FACENEUTRAL = REGISTRY.register("plate_faceneutral", PlateFaceneutralBlock::new);
	public static final DeferredBlock<Block> PLATE_FACECAT = REGISTRY.register("plate_facecat", PlateFacecatBlock::new);
	public static final DeferredBlock<Block> PLATE_INCORRECT = REGISTRY.register("plate_incorrect", PlateIncorrectBlock::new);
	public static final DeferredBlock<Block> PLATE_CORRECT = REGISTRY.register("plate_correct", PlateCorrectBlock::new);
	public static final DeferredBlock<Block> PLATE_DANGER = REGISTRY.register("plate_danger", PlateDangerBlock::new);
	public static final DeferredBlock<Block> PLATE_STOP = REGISTRY.register("plate_stop", PlateStopBlock::new);
	public static final DeferredBlock<Block> PLATE_BONUS = REGISTRY.register("plate_bonus", PlateBonusBlock::new);
	public static final DeferredBlock<Block> PLATE_FIRE = REGISTRY.register("plate_fire", PlateFireBlock::new);
	public static final DeferredBlock<Block> PLATE_WATER = REGISTRY.register("plate_water", PlateWaterBlock::new);
	public static final DeferredBlock<Block> PLATE_ELECTRICITY = REGISTRY.register("plate_electricity", PlateElectricityBlock::new);
	public static final DeferredBlock<Block> PLATE_HEART = REGISTRY.register("plate_heart", PlateHeartBlock::new);
	public static final DeferredBlock<Block> PLATE_LIGHT = REGISTRY.register("plate_light", PlateLightBlock::new);
	// Start of user code block custom blocks
	// End of user code block custom blocks
}