plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.pathmakersstudio.signplates'
version = '1.0.2'
base {
    archivesName = 'SignPlates-Forge-1.20.1'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'info'
            mods {
                sign_plates {
                    source sourceSets.main
                }
            }
        }

        client {}

        server {
            args '--nogui'
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', 'sign_plates', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    def replaceProperties = [
        minecraft_version: '1.20.1',
        forge_version_range: '[47,)',
        loader_version_range: '[47,)',
        mod_id: 'sign_plates',
        mod_name: 'Sign Plates',
        mod_license: 'All Rights Reserved',
        mod_version: project.version,
        mod_authors: 'MacatMovie',
        mod_description: 'This is your sign to sign bigger!'
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title'     : 'sign_plates',
            'Specification-Vendor'    : 'MacatMovie',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.version,
            'Implementation-Vendor'   : 'MacatMovie',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}
