org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.20.4
minecraft_version_range=[1.20.4]
neo_version=20.4.237
neo_version_range=[20.4.237,)
loader_version_range=[1,)
mod_id=sign_plates
mod_name=Sign Plates
mod_license=All Rights Reserved
mod_version=1.0.2
mod_group_id=com.pathmakersstudio.signplates
mod_authors=MacatMovie
mod_description=This is your sign to sign bigger!
