org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.21.12)
neo_version=21.11.42
neo_version_range=[21.11.42,)
loader_version_range=[1,)
mod_id=sign_plates
mod_name=Sign Plates
mod_license=All Rights Reserved
mod_version=1.0.3
mod_group_id=com.pathmakersstudio.signplates
mod_authors=MacatMovie
mod_description=This is your sign to sign bigger!
